### ISSUE TITLE
lowercase vs. uppercase pyCUFSM challenges during pip install

### ISSUE THREAD

**Issue by cristophermoen** [ClearCalcs/pyCUFSM#11]
Hello!

When I install pyCUFSM using 

python -m pip install git+https://github.com/ClearCalcs/pyCUFSM.git

the package comes in as pycufsm, not pyCUFSM.      A user needs to realize this when working with examples.  Maybe some instructions on the preferred package install method would help in the README.md.

Cris

**Comment by smith120bh** [comment]
Hi Cris,

This is fully intentional. A fully lower-case package name is per the naming standard of pypi.org, and was done in preparation for submitting pycufsm to pypi.org, so that it can be installed with a simple `pip install pycufsm` command.

However, this repository is still in an alpha state, meaning that it's not yet well-suited for anyone who's not an experienced programmer to use. While I do believe the FSM components generally work accurately and without error, it has not been well-tested yet. I plan to complete adding the original CUFSM validation cases to an automated testing suite on this repository, and then will "release" the package as a beta version onto pypi.org and add installation instructions for normal users. 

For right now, it is possible to see the repository's general functionality through either the example scripts in the root directory, or through its implementation on clearcalcs.com.

Brooks
